name: build-and-run-R
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("openair"), repos="https://cloud.r-project.org")'
      - name: Run your R script
        run: Rscript src/A1_2.R
